//flag is a boolean used to know if the user has clicked the cancel button or not
//when the window closes if the cancel event has not been triggered then it will be
//this prevents an infinite loop of canceling to occur
var flag = false;

//firebase.auth().signInWithEmailAndPassword("priver3@lsu.edu", "password"); // placeholder account for offline testing

//This event is triggered once the Authentication status of the user has been loaded.
//Creation of events, references, and varaibles that require Authentication to have
//already been loaded were placed within here.
//Callbacks are a possible alternative, but they proved difficult to implement
firebase.auth().onAuthStateChanged(function(user){
  if(user){
    var curPostType= ''; //variable that will hold the type of post to make it easier to find later

    //access the users database to gather necessary information
    //get the type of post from the database then find the user's post
    //onc the post is found in the database store the post's id for use later on
    firebase.database().ref('Users/' + user.uid).once('value', function(data){
      curPostType = data.val().curPostType;
      firebase.database().ref('Posts/' + curPostType + '/').once('value',function(data){
        data.forEach(function(child){
          if(child.val().uid === user.uid){
            var curPostId = child.key;
            firebase.database().ref('Users/' + user.uid ).update({curPostId});
          }
        });
      });
    });
    //create a reference to the cancel button
    var cancel = document.getElementById("cancel");
    //before the window closes if the flag is false then click the cancel button
    window.onbeforeunload = function(){
      if(!flag){
        cancel.click();
      }
    };


    //create an event listener for if an answerer enters the chat (the autogenerated message triggers this)
    firebase.database().ref('chats/'+ user.uid +'/txts').once('child_added', function(msg){
      //open a chat window
      window.open('chat.html');
      //close this tab
      window.open('','_self','');
      window.close();
    });


    //create an event for if the user wants to cancel the post
    cancel.addEventListener("click", function(){
      //set the flag to true and create the variables that will update the database information
      flag = true;
      var visibility = "hidden";
      var curChat = 'null';
      var curPostId  = 'null';
      curPostType= 'null';

      //reference the users database information
      firebase.database().ref('Users/' + user.uid).once('value', function(data){
        //get the information needed to find the post in the database
        var id = data.val().curPostId;
        var type=data.val().curPostType;

        //se the post's visibility to hidden and null out the chat specific fields in the database
        firebase.database().ref('Posts/' + type + '/' + id ).update({visibility});
        firebase.database().ref('Users/' + user.uid ).update({curChat});
        firebase.database().ref('Users/' + user.uid ).update({curPostId});
        firebase.database().ref('Users/' + user.uid ).update({curPostType});

        //close the tab
        window.open('','_self','');
        window.close();
      });
    });

  }
});
